#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
sys.path.append("C:\Users\Administrator\sdms\app\templates")
sys.path.append("C:\Users\Administrator\sdms\Lib\site-packages")
sys.path.append("C:\Users\Administrator\sdms\Lib")
sys.path.append("C:\\Users\\Administrator\\sdms\\app")

from main import start

if __name__ == "__main__":
    print sys.path
    start()
